import * as Types from '../../generated/graphql';

export type FeaturedImageFields_FlmsCourse_Fragment = { __typename?: 'FlmsCourse', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFields_FlmsExam_Fragment = { __typename?: 'FlmsExam', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFields_FlmsLesson_Fragment = { __typename?: 'FlmsLesson', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFields_FlmsTopic_Fragment = { __typename?: 'FlmsTopic', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFields_Page_Fragment = { __typename?: 'Page', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFields_Post_Fragment = { __typename?: 'Post', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFields_Product_Fragment = { __typename?: 'Product', featuredImage?: { __typename?: 'NodeWithFeaturedImageToMediaItemConnectionEdge', node: { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null } } | null };

export type FeaturedImageFieldsFragment = FeaturedImageFields_FlmsCourse_Fragment | FeaturedImageFields_FlmsExam_Fragment | FeaturedImageFields_FlmsLesson_Fragment | FeaturedImageFields_FlmsTopic_Fragment | FeaturedImageFields_Page_Fragment | FeaturedImageFields_Post_Fragment | FeaturedImageFields_Product_Fragment;

export type MediaItemFieldsFragment = { __typename?: 'MediaItem', id: string, databaseId: number, sourceUrl?: string | null, altText?: string | null, caption?: string | null, title?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null, sizes?: Array<{ __typename?: 'MediaSize', name?: string | null, width?: string | null, height?: string | null, sourceUrl?: string | null } | null> | null } | null };

export type ResponsiveImageFieldsFragment = { __typename?: 'MediaItem', id: string, sourceUrl?: string | null, altText?: string | null, srcSet?: string | null, sizes?: string | null, mediaDetails?: { __typename?: 'MediaDetails', width?: number | null, height?: number | null } | null };
