import * as Types from '../../generated/graphql';

export type FlexibleContentFieldsFragment = { __typename?: 'Page', flexibleContent?: { __typename?: 'FlexibleContent', flexibleContent?: Array<{ __typename: 'FlexibleContentFlexibleContentAccordionLayout' } | { __typename: 'FlexibleContentFlexibleContentAlternatingTextImageLayout' } | { __typename: 'FlexibleContentFlexibleContentBlockquoteLayout' } | { __typename: 'FlexibleContentFlexibleContentCtaButtonsLayout' } | { __typename: 'FlexibleContentFlexibleContentFlexibleGridLayout' } | { __typename: 'FlexibleContentFlexibleContentHeadingLayout', heading?: string | null, bandId?: string | null, bandClasses?: string | null, colorScheme?: Array<string | null> | null, textAlignment?: Array<string | null> | null } | { __typename: 'FlexibleContentFlexibleContentHeadingWysiwygRepeaterLayout' } | { __typename: 'FlexibleContentFlexibleContentHeroLayout', heading?: string | null, subheading?: string | null, bandId?: string | null, bandClasses?: string | null, colorScheme?: Array<string | null> | null, backgroundImage?: { __typename?: 'AcfMediaItemConnectionEdge', node: { __typename?: 'MediaItem', sourceUrl?: string | null, altText?: string | null } } | null } | { __typename: 'FlexibleContentFlexibleContentHtmlLayout' } | { __typename: 'FlexibleContentFlexibleContentImageModuleLayout' } | { __typename: 'FlexibleContentFlexibleContentListLayout' } | { __typename: 'FlexibleContentFlexibleContentMediaGalleryLayout' } | { __typename: 'FlexibleContentFlexibleContentOembedLayout' } | { __typename: 'FlexibleContentFlexibleContentShortcodeLayout' } | { __typename: 'FlexibleContentFlexibleContentTableLayout' } | { __typename: 'FlexibleContentFlexibleContentWysiwygLayout', content?: string | null, bandId?: string | null, bandClasses?: string | null, colorScheme?: Array<string | null> | null, textAlignment?: Array<string | null> | null } | null> | null } | null };

export type HeroLayoutFieldsFragment = { __typename?: 'FlexibleContentFlexibleContentHeroLayout', heading?: string | null, subheading?: string | null, bandId?: string | null, bandClasses?: string | null, colorScheme?: Array<string | null> | null, backgroundImage?: { __typename?: 'AcfMediaItemConnectionEdge', node: { __typename?: 'MediaItem', sourceUrl?: string | null, altText?: string | null } } | null };

export type HeadingLayoutFieldsFragment = { __typename?: 'FlexibleContentFlexibleContentHeadingLayout', heading?: string | null, bandId?: string | null, bandClasses?: string | null, colorScheme?: Array<string | null> | null, textAlignment?: Array<string | null> | null };

export type WysiwygLayoutFieldsFragment = { __typename?: 'FlexibleContentFlexibleContentWysiwygLayout', content?: string | null, bandId?: string | null, bandClasses?: string | null, colorScheme?: Array<string | null> | null, textAlignment?: Array<string | null> | null };
